import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import SignalCard from "../components/SignalCard.jsx";

export default function Signals() {
  const [signals, setSignals] = useState(null);

  useEffect(() => {
    fetch("/api/signals")
      .then((r) => r.json())
      .then(setSignals)
      .catch(() => setSignals([]));
  }, []);

  return (
    <>
      <div className="page-head">
        <h1>Free Signals</h1>
        <p>
          New automated technical analysis every 4 hours, plus manual calls from our
          trader. Premium members get real-time alerts —{" "}
          <Link to="/waitlist">join the waitlist</Link>.
        </p>
        <p style={{ fontSize: 13, marginTop: 8 }}>
          Signals tagged <strong>AUTO TA</strong> are generated by a rules-based
          technical engine (EMA trend + RSI + swing levels on real 4H candles), not
          by a human. Educational only — not financial advice.
        </p>
      </div>
      <section className="section">
        {!signals && <p className="loading">Loading signals…</p>}
        {signals && signals.length === 0 && (
          <p className="loading">No signals yet — first one drops today. Check back soon.</p>
        )}
        {signals && (
          <div className="grid">
            {signals.map((s) => <SignalCard key={s.id} s={s} />)}
          </div>
        )}
      </section>
    </>
  );
}
