const fmtTime = (iso) =>
  new Date(iso).toLocaleString("en-US", {
    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
  });

export default function SignalCard({ s }) {
  const isNoTrade = s.status === "no-trade" || s.direction === "NO TRADE";
  const dirClass = s.direction === "SHORT" ? "short" : "long";
  const windowOpen =
    s.entryValidUntil && s.status === "active" && new Date(s.entryValidUntil) > new Date();

  return (
    <div className="card signal">
      <div className="signal-head">
        <span className="sym">{s.symbol}</span>
        <span>
          {s.market === "spot" && <span className="tag spot">SPOT </span>}
          {(s.market === "futures" || !s.market) && !isNoTrade && <span className="tag futures">FUTURES </span>}
          {s.generatedBy === "auto" && <span className="tag auto">AUTO TA </span>}
          {s.status === "closed-win" && <span className="tag win">WIN ✓ </span>}
          {s.status === "expired" && <span className="tag expired">EXPIRED </span>}
          {!isNoTrade && <span className={`tag ${dirClass}`}>{s.direction}</span>}
          {isNoTrade && <span className="tag expired">NO TRADE</span>}
        </span>
      </div>

      {!isNoTrade && (
        <div className="signal-rows">
          <div><div className="label">Entry</div>{s.entry}</div>
          <div><div className="label">Target</div>{s.target}</div>
          <div><div className="label">Stop Loss</div>{s.stopLoss}</div>
          <div><div className="label">Timeframe</div>{s.timeframe} · {s.confidence} confidence</div>
        </div>
      )}

      {windowOpen && !isNoTrade && (
        <p className="entry-window">
          ⏱ Entry window open — take entry while price is in the zone, until{" "}
          <strong>{fmtTime(s.entryValidUntil)}</strong> (next 4H update)
        </p>
      )}

      {s.analysis && <p className="analysis">{s.analysis}</p>}
      <span className="meta">
        Posted {fmtTime(s.postedAt)}
        {s.generatedBy === "auto" && " · generated by our automated 4H technical engine"}
      </span>
    </div>
  );
}
